begin;

create table if not exists public.work_centers (
  id bigint generated by default as identity primary key,
  name text not null,
  address text,
  latitude double precision not null,
  longitude double precision not null,
  radius_meters numeric(8,2) not null default 150,
  created_at timestamptz not null default now()
);

create unique index if not exists work_centers_name_key on public.work_centers (lower(name));

alter table public.work_centers
drop constraint if exists work_centers_radius_positive_check;

alter table public.work_centers
add constraint work_centers_radius_positive_check
check (radius_meters > 0);

alter table public.employees
add column if not exists attendance_policy text not null default 'anywhere',
add column if not exists assigned_work_center_id bigint references public.work_centers(id) on delete set null;

alter table public.employees
drop constraint if exists employees_attendance_policy_check;

alter table public.employees
add constraint employees_attendance_policy_check
check (attendance_policy in ('anywhere', 'assigned_center', 'manual_only'));

alter table public.attendances
add column if not exists latitude double precision,
add column if not exists longitude double precision,
add column if not exists accuracy_meters numeric(8,2),
add column if not exists validated_work_center_id bigint references public.work_centers(id) on delete set null,
add column if not exists location_distance_meters numeric(10,2),
add column if not exists location_status text not null default 'not_required',
add column if not exists location_note text;

alter table public.attendances
drop constraint if exists attendances_location_status_check;

alter table public.attendances
add constraint attendances_location_status_check
check (
  location_status in (
    'not_required',
    'optional_captured',
    'optional_missing',
    'validated_center'
  )
);

alter table public.work_centers enable row level security;

drop policy if exists attendances_insert_own_or_admin on public.attendances;
create policy attendances_insert_own_or_admin
on public.attendances
for insert
to authenticated
with check (
  public.current_user_is_admin()
  or exists (
    select 1
    from public.employees e
    where e.id = employee_id
      and e.auth_user_id = auth.uid()
  )
);

drop policy if exists work_centers_select_assigned_or_admin on public.work_centers;
create policy work_centers_select_assigned_or_admin
on public.work_centers
for select
to authenticated
using (
  public.current_user_is_admin()
  or id in (
    select e.assigned_work_center_id
    from public.employees e
    where e.auth_user_id = auth.uid()
  )
);

drop policy if exists work_centers_insert_admin_only on public.work_centers;
create policy work_centers_insert_admin_only
on public.work_centers
for insert
to authenticated
with check (public.current_user_is_admin());

drop policy if exists work_centers_update_admin_only on public.work_centers;
create policy work_centers_update_admin_only
on public.work_centers
for update
to authenticated
using (public.current_user_is_admin())
with check (public.current_user_is_admin());

drop policy if exists work_centers_delete_admin_only on public.work_centers;
create policy work_centers_delete_admin_only
on public.work_centers
for delete
to authenticated
using (public.current_user_is_admin());

create or replace function public.calculate_distance_meters(
  lat1 double precision,
  lon1 double precision,
  lat2 double precision,
  lon2 double precision
)
returns double precision
language sql
immutable
as $$
  select 6371000 * 2 * asin(
    sqrt(
      power(sin(radians((lat2 - lat1) / 2)), 2)
      + cos(radians(lat1))
      * cos(radians(lat2))
      * power(sin(radians((lon2 - lon1) / 2)), 2)
    )
  );
$$;

grant execute on function public.calculate_distance_meters(double precision, double precision, double precision, double precision) to authenticated;

commit;
